language: php
sudo: false
php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - nightly

env:
  - NO_INTERACTION=1

before_script:
  - phpize && ./configure && make clean && make

script:
  - make test && if [ -f tests/001.diff ]; then echo "Tests failed" && exit 1; fi
  - make install
  - echo "extension = geohash.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - php example.php
